### ISSUE TITLE
iPhone 5 doesn't show the pictures that are on it

### ISSUE THREAD

**Issue by Pointedstick** [gphoto/libgphoto2#147] opened 2017-03-21 01:45 UTC
I was asked to file an issue here after I originally filed it on GNOME: https://bugzilla.gnome.org/show_bug.cgi?id=779433

The issue is that my iPhone 5 doesn't mount properly with gphoto: it shows up as empty, insteas of displaying all the pictures inside:

$ gvfs-ls gphoto2://[usb:001,008]/
$

There are a ton of attachments with debug info available at https://bugzilla.gnome.org/show_bug.cgi?id=779433

**Comment by Sija** [comment] 2017-03-21 05:13
Do you use iOS 10.2? If so, there's opened issue #132 for you to checkout :)

**Comment by msmeissn** [comment] 2017-03-21 07:33
duplicate of issue #132

**Closed by msmeissn** 2017-03-21 07:33 UTC

**Comment by Pointedstick** [comment] 2017-03-21 13:58
Looks like that's it.
